---
- name: Create keypar
  os_keypar:
    name: "{{ key_name }}"
    auth:
      auth_url: "{{ url_to_auth }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      project_name: "{{ admin }}"
    state: present
    public_key_file: /opt/stack/.ssh/id_rsa.pub
